### ISSUE TITLE
Need to update your docker image due to api change in service manager

### ISSUE THREAD

**Issue by chapmanc** [Peripli/service-broker-proxy-cf#34]
Your last image on master was built 24 days ago: https://quay.io/repository/service-manager/sb-proxy-cf?tab=tags

But master here references a different api key so service_brokers call is returning 0 brokers
https://github.com/Peripli/service-broker-proxy/commit/644d04dafc3126356d1e101176f11ee7df0206cf

**Comment by pankrator** [comment]
We'll make a release today, so the latest core-proxy library will be adopted in the cf-proxy.

**Comment by dzahariev** [comment]
Release is created on schedule each 2 weeks. I am closing this.
